{% set name = "apache-airflow-providers-microsoft-mssql" %}
{% set version = "3.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_microsoft_mssql-{{ version }}.tar.gz
  sha256: ab7457703e976530ed688e1ee7fa8c5b219e8559b56df5efeaa9c923c09561e5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow-providers-common-sql >=1.3.1
    - apache-airflow >=2.6.0
    - pymssql >=2.1.8

test:
  imports:
    - airflow.providers.microsoft.mssql
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-microsoft-mssql for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/microsoft/mssql/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-microsoft-mssql/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
